### ISSUE TITLE
想新加about或者简历页面应该怎么弄呢？

### ISSUE THREAD

**Issue by chaneyandyou** [jonashao/hexo-theme-pteris#2]
想新加about或者简历页面应该怎么弄呢？谢谢

**Comment by jonashao** [comment]
你好@chaneyandyou，请参考这篇文档：[添加About页面](https://github.com/jonashao/hexo-theme-pteris/blob/master/doc/new-page.md)。
页面内容暂时就跟post内容一样。
如果想更具体定制页面，可以修改/pteris/layout/page.njk
做法如下：
1. 为about页面编辑单独的模板。 创建 /pteris/layout/macro/about.njk
```
{% macro render(page) %}
    <div id="about">
    // 你的内容
    </div>
{% endmacro %}
```

2. 判断页面类型，若类型为`about`，则用第一步创建的模板渲染
```
{% extends "includes/layout.njk" %}
{% import './macro/about.njk' as about_template %}

{% block main %}
    {% if page.type === 'about' %}
        {{ about_template.render(page) }}
    {% endif %}
{% endblock %}
```
