### ISSUE TITLE
nunjunks api

### ISSUE THREAD

**Issue by teekcode** [jonashao/hexo-theme-pteris#3]
I saw that you using {{ date(post.date) }}, but I didn't see any macro imported or nunjuns built-in filter in its docs, so my njks templates render can't parse that function, how can it word? thx

**Comment by jonashao** [comment]
hi, teek. it's a hexo's [helper function ](https://hexo.io/docs/helpers.html#date),
I don't exactly know how it works, but I think[ this doc](https://hexo.io/api/helper.html) may be helpful.

**Comment by teekcode** [comment]
finally got why njks can't prase those helper functions in my case -- I use them in macro. It seems that those function can only get from `outside`. Might be a bug in hexo-renderer-njks or the limitation of macro.
