### ISSUE TITLE
格式乱了

### ISSUE THREAD

**Issue by CrusherWu** [jonashao/hexo-theme-pteris#4]
1.显示格式乱了是怎么回事？
2.bower install 无法执行该命令

**Comment by jonashao** [comment]
1. 请问是升级模板还是第一次使用模板？
如果第一次使用的话，需要安装nunjucks渲染引擎
        npm install --save hexo-renderer-njks
不是这个问题的话请问可以详细描述一下哪里格式乱了吗？
2. 如果bower install 命令是在themes/pteris目录下，请问可以提供报错内容吗？

**Comment by CrusherWu** [comment]
1.nunjucks渲染引擎已经安装了
http://ojclrjct5.bkt.clouddn.com/1489422309.png
2.报错内容：
MacdeMacBook-Air:blog mac$ cd themes/pteris
MacdeMacBook-Air:pteris mac$ bower install
-bash: bower: command not found
MacdeMacBook-Air:pteris mac$

**Comment by jonashao** [comment]
你需要先安装bower，
$ npm install -g bower

**Comment by CrusherWu** [comment]
bower安装后，bower install 可以执行，不过现在无法将本地博客部署到git上。http://ojclrjct5.bkt.clouddn.com/1489464050.png

**Comment by jonashao** [comment]
也许是因为没有安装git插件。
在博客根目下（不是主题目录）：
    npm install hexo-deployer-git --save

**Comment by CrusherWu** [comment]
并不是 can not found git ,还没更换主题的时候是可以部署上去的
http://ojclrjct5.bkt.clouddn.com/1489465265.png

**Comment by jonashao** [comment]
如果换回以前主题还有这个错误，可能是git的密钥出了问题，或者因为长城防火墙。

**Comment by CrusherWu** [comment]
不行呢
现在想重新搭建，hexo都没法卸载

**Comment by jonashao** [comment]
为了避免类似的问题，我已在新版本中移除了对bower的依赖。
现在关闭这个issue，如还有格式错乱的问题请继续回复。
